work-report/src/main/java/com/cy/work/backend/web/common/WorkProjectTagItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.backend.web.common.setting.WorkProjectTagItemSetting;
import com.cy.work.backend.web.logic.manager.WorkSettingOrgManager;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 標籤Item Bean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("request")
@Slf4j
@ManagedBean
public class WorkProjectTagItemBean implements Serializable {

    
    private static final long serialVersionUID = -101415460354603778L;

    @Autowired
    private WorkSettingOrgManager workSettingOrgManager;

    /** 取得 標籤SelectItems */
    public List<SelectItem> getWorkProjectTagItems() {
        try {
            return WorkProjectTagItemSetting.getWorkProjectTagItems(workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getWorkProjectTagItems ERROR", e);
        }
        return Lists.newArrayList();
    }

    public List<SelectItem> getActiveWorkProjectTagItems() {
        try {
            Integer loginUserDepSid = SecurityFacade.getPrimaryOrgSid();
            return WorkProjectTagItemSetting.getActiveWorkProjectTagItems(loginUserDepSid,
                    workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getActiveWorkProjectTagItems ERROR", e);
        }
        return Lists.newArrayList();
    }

    /** 標籤名稱 By tagID */
    public String getWorkProjectTagName(String tagID) {
        try {
        return WorkProjectTagItemSetting.getWorkProjectTagName(tagID,
                workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getWorkProjectTagName ERROR", e);
        }
        return "";
    }
}

work-report/src/main/java/com/cy/work/backend/web/common/WorkRrojectStatusItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.work.backend.web.common.setting.WRStatusSetting;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@ManagedBean
public class WorkRrojectStatusItemBean implements Serializable{


    private static final long serialVersionUID = -5075911796932972813L;

    public List<SelectItem> getWorkSearchStatusItems() {
        return WRStatusSetting.getWorkSearchItems();
    }

}

work-report/src/main/java/com/cy/work/backend/web/web/view/Search10Bean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.web.view;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.backend.web.common.ExportExcelComponent;
import com.cy.work.backend.web.listener.DataTableReLoadCallBack;
import com.cy.work.backend.web.listener.MessageCallBack;
import com.cy.work.backend.web.listener.TableUpDownListener;
import com.cy.work.backend.web.listener.TraceUpdateCallBack;
import com.cy.work.backend.web.listener.TransUpdateCallBack;
import com.cy.work.backend.web.logic.components.OrgLogicComponents;
import com.cy.work.backend.web.logic.components.WRTransSearchWorkReportLogicComponents;
import com.cy.work.backend.web.logic.components.WRUserLogicComponents;
import com.cy.work.backend.web.logic.components.WRReportCustomColumnLogicComponents;
import com.cy.work.backend.web.util.SpringContextHolder;
import com.cy.work.backend.web.util.pf.DisplayController;
import com.cy.work.backend.web.view.components.CustomColumnComponent;
import com.cy.work.backend.web.view.components.WRTraceComponent;
import com.cy.work.backend.web.view.components.WRTransTableComponent;
import com.cy.work.backend.web.view.components.WorkReportTransSearchComponent;
import com.cy.work.backend.web.view.vo.OrgViewVo;
import com.cy.work.backend.web.view.vo.UserViewVO;
import com.cy.work.backend.web.view.vo.WRTransIncomeSearchColumnVO;
import com.cy.work.backend.web.view.vo.WRTransIncomeVO;
import com.cy.work.backend.web.view.vo.WorkReportSidTo;
import com.cy.work.backend.web.vo.enums.WRIncomeTransSearchColumn;
import com.cy.work.backend.web.vo.enums.WRReadStatus;
import com.cy.work.backend.web.vo.enums.WRReportCustomColumnUrlType;
import com.cy.work.common.utils.WkJsonUtils;
import com.cy.work.common.utils.WkStringUtils;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.omnifaces.util.Faces;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@Slf4j
@ManagedBean
public class Search10Bean implements Serializable, TableUpDownListener {


    private static final long serialVersionUID = 3760535883700844358L;
    @Getter
    private UserViewVO userViewVO;
    @Getter
    private OrgViewVo depViewVo;
    @Getter
    private OrgViewVo compViewVo;
    @Getter
    private WorkReportTransSearchComponent workReportTransSearchComponent;
    @Getter
    private CustomColumnComponent customColumn;
    /** view 顯示錯誤訊息 */
    @Getter
    private String errorMessage;
    @Getter
    private final String dataTableID = "dataTableIncomeReport";
    @Getter
    private final String dataTableWv = "dataTableIncomeReportWv";
    @Setter
    @Getter
    private boolean showFrame = false;
    @Getter
    private String iframeUrl = "";
    @Autowired
    private WRReportCustomColumnLogicComponents wrReportCustomColumnLogicComponents;
    @Getter
    private WRTransIncomeSearchColumnVO searchColumnVO;
    @Autowired
    private TableUpDownBean tableUpDownBean;
    @Getter
    private List<WRTransIncomeVO> transIncomeVOs;
    @Setter
    @Getter
    private WRTransIncomeVO selWRTransIncomeVO;

    private List<WRTransIncomeVO> tempWRTransIncomeVOs;

    private String tempSelSid;
    @Autowired
    private WRTransSearchWorkReportLogicComponents wRTransSearchWorkReportLogicComponents;
    @Getter
    private WRTraceComponent traceComponent;

    private String selWr_ID;
    @Getter
    private WRTransTableComponent transTableComponent;
    @Autowired
    private ExportExcelComponent exportExcelComponent;
    @Getter
    private boolean hasDisplay = true;

    @PostConstruct
    public void init() {
        userViewVO = WRUserLogicComponents.getInstance().findBySid(SecurityFacade.getUserSid());
        depViewVo = OrgLogicComponents.getInstance().findBySid(SecurityFacade.getPrimaryOrgSid());
        compViewVo = OrgLogicComponents.getInstance().findById(SecurityFacade.getCompanyId());
        this.traceComponent = new WRTraceComponent(userViewVO.getSid(), messageCallBack, traceUpdateCallBack);
        this.transTableComponent = new WRTransTableComponent(userViewVO.getSid(), compViewVo.getSid(), transUpdateCallBack, messageCallBack);
        searchColumnVO = wrReportCustomColumnLogicComponents.getWRTransIncomeReportSearchColumnSetting(userViewVO.getSid());
        boolean showSelectBaseOrg = false;
        String personTitleName = "寄發者";
        String selectAllOrgTitleName = "寄發單位";
        boolean showSelectTransType = false;
        workReportTransSearchComponent = new WorkReportTransSearchComponent(compViewVo.getSid(), userViewVO.getSid(), showSelectBaseOrg, personTitleName, selectAllOrgTitleName, showSelectTransType);
        settingDefault();
        customColumn = new CustomColumnComponent(WRReportCustomColumnUrlType.INCOME_REPORT_SEARCH, Arrays.asList(WRIncomeTransSearchColumn.values()), searchColumnVO.getPageCount(), userViewVO.getSid(), messageCallBack, dataTableReLoadCallBack);
        doSearch();
    }

    public void clear() {
        settingDefault();
        doSearch();
    }

    /**
     * 匯出excel
     *
     * @param document excel物件
     */
    public void exportExcel(Object document) {
        try {
            exportExcelComponent.exportExcel(document, null,
                    null, "收呈報", false);
        } catch (Exception e) {
            log.error("exportExcel", e);
        } finally {
            hasDisplay = true;
        }
    }

    public void hideColumnContent() {
        hasDisplay = false;
    }

    public void settingDefault() {
        workReportTransSearchComponent.settingDefault();
        workReportTransSearchComponent.getWorkReportSearchHeaderComponent().changeDateIntervalToday();
    }

    public void doSearch() {
        try {
            transIncomeVOs = runSearch("");
            if (transIncomeVOs.size() > 0) {
                DisplayController.getInstance().execute("selectDataTablePage('" + dataTableWv + "',0);");
            }
        } catch (Exception e) {
            log.error("doSearch", e);
            messageCallBack.showMessage(e.getMessage());
        }
    }

    private List<WRTransIncomeVO> runSearch(String wr_id) {
        List<Integer> selectAllOrgSids = Lists.newArrayList();
        workReportTransSearchComponent.getSelectAllOrgs().forEach(item -> selectAllOrgSids.add(item.getSid()));
        // return Lists.newArrayList();
        return wRTransSearchWorkReportLogicComponents.getWRTransIncomeReport(
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getSelectTag(),
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getReadStatus(),
                selectAllOrgSids,
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getPersonName(),
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getTitle(),
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getContent(),
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getAllSearchText(),
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getStartDate(),
                workReportTransSearchComponent.getWorkReportSearchHeaderComponent().getEndDate(),
                userViewVO.getSid(),
                depViewVo.getSid(),
                wr_id, compViewVo.getSid()
        );
    }

    public void clickTransDep(String sid) {
        try {
            List<WRTransIncomeVO> sel = transIncomeVOs.stream()
                    .filter(each -> each.getSid().equals(sid))
                    .collect(Collectors.toList());
            if (WkStringUtils.isEmpty(sel)) {
                messageCallBack.showMessage("轉寄部門資料比對有誤,無法開啟");
                return;
            }
            selWRTransIncomeVO = sel.get(0);
            selWr_ID = selWRTransIncomeVO.getWr_id();
            DisplayController.getInstance().update(dataTableID);
            transTableComponent.loadDataDep(selWRTransIncomeVO.getWr_id(), selWRTransIncomeVO.getNo());
            DisplayController.getInstance().showPfWidgetVar("dlgForwardDep");
        } catch (Exception e) {
            log.error("clickTransDep", e);
        }
    }

    public void clickTransPerson(String sid) {
        try {
            List<WRTransIncomeVO> sel = transIncomeVOs.stream()
                    .filter(each -> each.getSid().equals(sid))
                    .collect(Collectors.toList());
            if (WkStringUtils.isEmpty(sel)) {
                messageCallBack.showMessage("轉寄個人資料比對有誤,無法開啟");
                return;
            }

            selWRTransIncomeVO = sel.get(0);
            selWr_ID = selWRTransIncomeVO.getWr_id();
            DisplayController.getInstance().update(dataTableID);
            transTableComponent.loadDataPerson(selWRTransIncomeVO.getWr_id(), selWRTransIncomeVO.getNo());
            DisplayController.getInstance().showPfWidgetVar("dlgForwardPerson");
        } catch (Exception e) {
            log.error("clickTransDep", e);
        }
    }

    public void clickTrace(String sid) {
        try {
            List<WRTransIncomeVO> sel = transIncomeVOs.stream()
                    .filter(each -> each.getSid().equals(sid))
                    .collect(Collectors.toList());
            if (WkStringUtils.isEmpty(sel)) {
                messageCallBack.showMessage("轉寄個人資料比對有誤,無法開啟");
                return;

work-report/src/main/webapp/search/search2_custom.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:cp="http://java.sun.com/jsf/composite/components"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<p:dialog widgetVar="dlgReportCustomFilter" header="自訂預設搜尋條件"
	resizable="false" position="right top" modal="true">
	<p:outputPanel id="dlgReportCustomFilter_view" style="overflow: hidden;">
		<p:scrollPanel style="height:400px; width: 400px;" mode="native">
			<p:panelGrid>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="標籤 ： " /></p:column>
					<p:column>
						<p:selectOneMenu value="#{search2Bean.customClauseVO.selectTag}" style="width: 80px;">
							<f:selectItem itemLabel="請選擇" itemValue="" />
							<f:selectItems value="#{workProjectTagItemBean.workProjectTagItems}" />
						</p:selectOneMenu>
					</p:column>
				</p:row>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="單據狀態 ： " /></p:column>
					<p:column>
						<p:selectOneMenu value="#{search2Bean.customClauseVO.selectStatus}" style="width:80px;" >
						    <f:selectItem itemLabel="全部" itemValue=""/>
						    <f:selectItems value="#{workRrojectStatusItemBean.workSearchStatusItems}"/>
						</p:selectOneMenu>
					</p:column>
				</p:row>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="主題 ： " /></p:column>
					<p:column>
						<p:inputText value="#{search2Bean.customClauseVO.title}" />
					</p:column>
				</p:row>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="內容 ： " /></p:column>
					<p:column>
						<p:inputText value="#{search2Bean.customClauseVO.content}" />
					</p:column>
				</p:row>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="建立人員 ： " /></p:column>
					<p:column>
						<p:inputText value="#{search2Bean.customClauseVO.personName}" />
					</p:column>
				</p:row>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="日期撈取 ： " /></p:column>
					<p:column>
						<p:selectOneMenu value="#{search2Bean.customClauseVO.sqlColumnType}"  style="width: 150px;">
						    <f:selectItem itemLabel="建立區間" itemValue="WT_CREATE_DATE"/>
						    <f:selectItem itemLabel="異動區間" itemValue="WT_UPDATE_DATE"/>
						    <p:ajax event="change" listener="#{search2Bean.dateTimeTypeOnChange('popup')}" 
								    onstart="showLoad();" oncomplete="hideLoad();"
								    process="@this" update="dlgReportCustomFilter_view"/>
						</p:selectOneMenu>
					</p:column>
				</p:row>
				<p:row>
					<p:column style="text-align:right;"><h:outputText value="排序方式 ： " /></p:column>
					<p:column>
						<p:selectOneMenu value="#{search2Bean.customClauseVO.order}"  style="width: 150px;">
						    <f:selectItem itemLabel="舊 > 新 排序" itemValue="ASC"/>
						    <f:selectItem itemLabel="新 > 舊 排序" itemValue="DESC"/>
						</p:selectOneMenu>
					</p:column>
				</p:row>
				<p:row>
					<p:column colspan="2">
						<p:selectOneButton id="dateSelectItemButton" value="#{search2Bean.customClauseVO.dateTypeIndex}">
							<f:selectItem itemLabel="上個月" itemValue="0" />
							<f:selectItem itemLabel="本月份" itemValue="1" />
							<f:selectItem itemLabel="下個月" itemValue="2" />
							<f:selectItem itemLabel="前一日" itemValue="3" />
						</p:selectOneButton>
						<p:commandButton value="清除" process="@this" update="dateSelectItemButton"
							onstart="showLoad();" oncomplete="hideLoad();"
							actionListener="#{search2Bean.clearDateBtnIndex()}" />
					</p:column>
				</p:row>
			</p:panelGrid>
		</p:scrollPanel>
		<p:panelGrid>
			<p:column colspan="2">
				<p:commandButton value="確定"
					actionListener="#{search2Bean.saveCustomClause()}"
					process="@this dlgReportCustomFilter_view" update="headerTitle #{search2Bean.dataTableID}"
					onclick="showLoad();" oncomplete="hideLoad();PF('dlgReportCustomFilter').hide()" />
				<p:commandButton value="取消" process="@this"
					onclick="PF('dlgReportCustomFilter').hide()" />
			</p:column>
		</p:panelGrid>

	</p:outputPanel>
</p:dialog>
</html>