work-report/src/main/java/com/cy/work/backend/web/controller/component/mipker/vo/MultItemPickerShowMode.java
/**
 * 
 */
package com.cy.work.backend.web.controller.component.mipker.vo;

import lombok.Getter;

/**
 * @author allen1214_wu
 *
 */
public enum MultItemPickerShowMode {

    LIST("列表模式"),
    TREE("樹模式");

    /** 欄位名稱 */
    @Getter
    private final String label;

    MultItemPickerShowMode(String label) {
        this.label = label;
    }
    
}

work-report/src/main/java/com/cy/work/backend/web/controller/component/mipker/vo/MultItemPickerTreeVO.java
/**
 * 
 */
package com.cy.work.backend.web.controller.component.mipker.vo;

import java.io.Serializable;
import java.util.Map;

import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

import com.cy.work.common.vo.WkItem;
import com.google.common.collect.Maps;

import lombok.Getter;
import lombok.Setter;

/**
 * @author allen1214_wu
 *
 */
public class MultItemPickerTreeVO implements Serializable{



    private static final long serialVersionUID = 1855233584919872315L;

    /**
     * 有樹狀顯示模式
     */
    @Setter
    @Getter
    private boolean hasTreeMode = false;
    
    /**
     * 是否全選
     */
    @Getter
    @Setter
    private boolean allSelected = false;
    
    /**
     * 樹節點結構資料
     */
    @Getter
    @Setter
    private TreeNode rootNode = new DefaultTreeNode();
    
    

    /**
     * 畫面傳入選擇的節點
     */
    @Getter
    @Setter
    private TreeNode[] selectedNodes;
    

    @Getter
    @Setter
    private String serachItemNameKeyword;
    
    @Getter
    private Map<WkItem, TreeNode> treeNodeMapByItem = Maps.newLinkedHashMap();
    
}

work-report/src/main/java/com/cy/work/backend/web/controller/component/mipker/vo/MultItemPickerVO.java
/**
 * 
 */
package com.cy.work.backend.web.controller.component.mipker.vo;

import java.io.Serializable;
import java.util.List;

import com.cy.work.common.vo.WkItem;
import com.google.common.collect.Lists;

import lombok.Getter;
import lombok.Setter;

/**
 * @author allen1214_wu
 *
 */
public class MultItemPickerVO implements Serializable {

    
    private static final long serialVersionUID = 845561509677332090L;

    /**
     * 所有項目
     */
    @Getter
    @Setter
    private List<WkItem> allItems = Lists.newArrayList();

    /**
     * 被選擇的項目
     */
    @Getter
    @Setter
    private List<WkItem> selectedItems = Lists.newArrayList();

    /**
     * 過濾後的項目
     */
    @Getter
    @Setter
    private List<WkItem> filteredItems;

    /**
     * 清空已選擇, 和過濾項目
     */
    public void initSelectedAndfiltered() {
        this.selectedItems = Lists.newArrayList();
        this.filteredItems = allItems;
    }

}

work-report/src/main/java/com/cy/work/backend/web/common/WorkProjectAcceptEditItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.work.backend.web.common.setting.WorkProjectAcceptEditSetting;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 編輯權限Item Bean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@ManagedBean
public class WorkProjectAcceptEditItemBean implements Serializable {

    
    private static final long serialVersionUID = 1579330284769456699L;

    /** 取得 編輯權限SelectItems */
    public List<SelectItem> getWorkProjectAcceptEditItems() {
        return WorkProjectAcceptEditSetting.getWorkProjectAcceptEditItems();
    }

    /** 編輯權限名稱 By key */
    public String getWorkProjectAcceptEditName(String key) {
        return WorkProjectAcceptEditSetting.getWorkProjectAcceptEditName(key);
    }
}

work-report/src/main/java/com/cy/work/backend/web/common/WorkProjectTagItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.backend.web.common.setting.WorkProjectTagItemSetting;
import com.cy.work.backend.web.logic.manager.WorkSettingOrgManager;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 標籤Item Bean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("request")
@Slf4j
@ManagedBean
public class WorkProjectTagItemBean implements Serializable {

    
    private static final long serialVersionUID = -101415460354603778L;

    @Autowired
    private WorkSettingOrgManager workSettingOrgManager;

    /** 取得 標籤SelectItems */
    public List<SelectItem> getWorkProjectTagItems() {
        try {
            return WorkProjectTagItemSetting.getWorkProjectTagItems(workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getWorkProjectTagItems ERROR", e);
        }
        return Lists.newArrayList();
    }

    public List<SelectItem> getActiveWorkProjectTagItems() {
        try {
            Integer loginUserDepSid = SecurityFacade.getPrimaryOrgSid();
            return WorkProjectTagItemSetting.getActiveWorkProjectTagItems(loginUserDepSid,
                    workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getActiveWorkProjectTagItems ERROR", e);
        }
        return Lists.newArrayList();
    }

    /** 標籤名稱 By tagID */
    public String getWorkProjectTagName(String tagID) {
        try {
        return WorkProjectTagItemSetting.getWorkProjectTagName(tagID,
                workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getWorkProjectTagName ERROR", e);
        }
        return "";
    }
}

work-report/src/main/java/com/cy/work/backend/web/common/attachment/AttachServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common.attachment;

import com.cy.work.backend.web.logic.utils.attachment.AttachmentUtils;
import com.cy.work.backend.web.logic.vo.AttachmentVO;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.MessageFormat;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 附件預覽元件
 * @author brain0925_liao
 */
public interface AttachServlet {
    
    public final static String PARAM_SID_KEY = "sid";
    public final static String PARAM_TIME_KEY = "time";
    public final static String PARAM_ATTACH_SERVICE_KEY = "service";
    
    final Logger logger = LoggerFactory.getLogger(AttachServlet.class);
    
    default void doGet(HttpServletRequest request, HttpServletResponse response, ServletContext servletContext) throws ServletException, IOException {
        Object attachmentSid = this.findAttachSid(request);
        String uploadTime = this.getUploadTimeParameter(request);
        AttachmentVO attachment = this.getAttachAttachmentVOBySid(attachmentSid);
        File attachmentFile = this.getServerSideFile(attachment);
        if (!this.validateParameters(attachment, uploadTime, attachmentFile)) {
            response.setStatus(HttpServletResponse.SC_NOT_FOUND);
            return;
        }
        this.sendAttachment(request, response, servletContext, attachment, attachmentFile);
    }
    
    default void sendAttachment(HttpServletRequest request, HttpServletResponse response, ServletContext servletContext,
            AttachmentVO attachment, File attachmentFile) throws IOException {
        String encodedFileName = AttachmentUtils.encodeFileName(attachment.getAttName());
        String mimeType
                = AttachmentUtils.getNoneNullMimeType(servletContext, attachment.getAttName());
        String contentDispositionPattern
                = AttachmentUtils.isMSIE(request)
                ? "{0}; filename=\"{1}\""
                : "{0}; filename=\"{1}\"; filename*=UTF-8''''\"{1}\"";
        String contentDisposition
                = MessageFormat.format(contentDispositionPattern, "inline", encodedFileName);
        FileInputStream in = new FileInputStream(attachmentFile);
        OutputStream out = response.getOutputStream();
        
        response.setContentType(mimeType);
        response.setContentLength((int) attachmentFile.length());
        response.setHeader("Content-Disposition", contentDisposition);
        
        try {
            IOUtils.copy(in, out);
            out.flush();
        } finally {
            IOUtils.closeQuietly(in);
        }
    }
    
    default boolean validateParameters(AttachmentVO attachment, String uploadTime, File attachmentFile) {
        // 檢查 attachment.getCreated() 是為了預防使用者從 URL 修改 sid 即可取得其他檔案.
        return checkParam(attachment, uploadTime, attachmentFile)
                && uploadTime.equals(attachment.getParamCreateTime())
                && checkAttachmentFile(attachmentFile);
    }
    
    default boolean checkParam(AttachmentVO attachment, String uploadTime, File attachmentFile) {
        return attachment != null && uploadTime != null && attachmentFile != null;
    }
    
    default boolean checkAttachmentFile(File attachmentFile) {
        return attachmentFile.exists() && attachmentFile.isFile();
    }
    
    public AttachmentVO getAttachAttachmentVOBySid(Object attachmentSid);
    
    public File getServerSideFile(AttachmentVO attachment);
    
    default Object findAttachSid(HttpServletRequest request) {
        return this.getAttachmentSidParameter(request);
    }
    
    default String getAttachmentServiceParameter(HttpServletRequest request) {
        return request.getParameter(PARAM_ATTACH_SERVICE_KEY);
    }
    
    default String getAttachmentSidParameter(HttpServletRequest request) {
        return request.getParameter(PARAM_SID_KEY);
    }
    
    default String getUploadTimeParameter(HttpServletRequest request) {
        try {
            String timeString = request.getParameter(PARAM_TIME_KEY);
            return timeString;
        } catch (Exception e) {
            logger.error("getUploadTimeParameter Error ", e);
            System.err.println("錯誤：" + e.getMessage());
            return "";
        }
    }
}

work-report/src/main/java/com/cy/work/backend/web/common/attachment/WPAttachServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common.attachment;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.common.vo.basic.BasicAttachmentService;
import com.cy.work.common.vo.basic.BasicAttachmentServlet;
import com.cy.work.backend.web.logic.components.WRAttachmentLogicComponents;
import com.cy.work.backend.web.logic.components.OrgLogicComponents;
import com.cy.work.backend.web.logic.components.WRUserLogicComponents;
import com.cy.work.backend.web.logic.components.WRMasterLogicComponents;
import com.cy.work.backend.web.listener.MessageCallBack;
import com.cy.work.backend.web.listener.PreviousAndNextCallBack;
import com.cy.work.backend.web.view.components.WorkReportViewComponent;
import com.cy.work.backend.web.view.vo.OrgViewVo;
import com.cy.work.backend.web.view.vo.UserViewVO;
import com.cy.work.backend.web.vo.WRAttachment;
import com.cy.work.backend.web.vo.WRMaster;
import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author brain0925_liao
 */
@WebServlet("/WPAttachServlet")
@Slf4j
public class WPAttachServlet extends HttpServlet implements BasicAttachmentServlet {

    
    private static final long serialVersionUID = -8173637133153556453L;

    //要覆寫
    public final static String SERVLET_NAME = WPAttachServlet.class.getSimpleName();
    
    private final String illegal_readPath = "/error/illegal_read.xhtml";

    @SuppressWarnings("rawtypes")
    @Override
    public BasicAttachmentService getAttachService(HttpServletRequest request) {
        return WRAttachmentLogicComponents.getInstance();
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        if (SecurityFacade.getUserSid() == null || SecurityFacade.getUserSid() <= 0) {
            response.sendRedirect(request.getContextPath() + illegal_readPath);
            log.error("無登入");
            return;
        }

        UserViewVO userViewVO = WRUserLogicComponents.getInstance().findBySid(SecurityFacade.getUserSid());
        OrgViewVo depViewVo = OrgLogicComponents.getInstance().findBySid(SecurityFacade.getPrimaryOrgSid());
        OrgViewVo compViewVo = OrgLogicComponents.getInstance().findById(SecurityFacade.getCompanyId());
        WorkReportViewComponent workReportViewComponent = new WorkReportViewComponent(userViewVO, depViewVo, compViewVo, messageCallBack, previousAndNextCallBack);
        String attachmentSid = (String) this.findAttachSid(request);
        WRAttachment attachment = WRAttachmentLogicComponents.getInstance().getWRAttachmentBySid(attachmentSid);
        WRMaster wr = WRMasterLogicComponents.getInstance().getWRMasterBySid(attachment.getWr_sid());
        boolean checkPermission = workReportViewComponent.checkViewWorkReportPermission(wr);
        if (!checkPermission) {
            response.sendRedirect(request.getContextPath() + illegal_readPath);
            log.error("無權限");
            return;
        }

        BasicAttachmentServlet.super.doGet(request, response, super.getServletContext());
    }

    @Override
    public Object findAttachSid(HttpServletRequest request) {
        return String.valueOf(this.getAttachmentSidParameter(request));
    }

    private PreviousAndNextCallBack previousAndNextCallBack = new PreviousAndNextCallBack() {
        /**
         * 
         */
        private static final long serialVersionUID = 3386339989538319929L;

        @Override
        public void doPrevious() {
        }

        @Override
        public void doNext() {
        }
    };

    private final MessageCallBack messageCallBack = new MessageCallBack() {
        /**
         * 
         */
        private static final long serialVersionUID = 6271258645761527981L;

        @Override
        public void showMessage(String m) {
        }
    };

}

work-report/src/main/webapp/resources/components/attachmentView.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:cc="http://java.sun.com/jsf/composite">

    <cc:interface>
        <cc:attribute name="model" shortDescription="附加檔案模型物件" required="true" />
    </cc:interface>
    <cc:implementation>
        <p:outputPanel>
        <p:dataList id="ath_file_list_id" class="datalist-noborder" 
                    value="#{cc.attrs.model.oneTimeUploadAttachmentVOs}" var="attach" type="definition" >
            <p:panelGrid columns="3">
                <p:selectBooleanCheckbox value="#{attach.checked}" >
                    <p:ajax onstart="showLoad();"
                            process="ath_file_list_id" 
                            listener="#{cc.attrs.model.changeCheckbox()}" 
                            oncomplete="hideLoad();"
                            update="ath_file_list_id"
                            />
                </p:selectBooleanCheckbox>
                 <p:outputLabel value="#{attach.attName}"/>
                 <p:inputText value="#{attach.attDesc}"
                             maxlength="255" style="width: 500px"/>
            </p:panelGrid>
        </p:dataList>
            </p:outputPanel>
    </cc:implementation>
</ui:composition>

work-report/src/main/webapp/resources/components/inboxGroupItem.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:cp="http://java.sun.com/jsf/composite/components"
                xmlns:cc="http://java.sun.com/jsf/composite">

    <cc:interface>

        <cc:attribute name="model" type="com.cy.work.backend.web.view.components.WorkInboxComponent" shortDescription="欄位調整模型物件" required="true" />
        <cc:attribute name="accId" 
                      required="true" 
                      shortDescription="accpanel id and widgetVar" 
                      />
    </cc:interface>
    <cc:implementation>
        <p:accordionPanel value="#{cc.attrs.model.sentBackups}"
                          var="inboxGroup"
                          multiple="true"
                          dynamic="false"
                          id="#{cc.attrs.accId}"
                          widgetVar="#{cc.attrs.accId}"
                          activeIndex="0"
                          >
            <p:tab>
                <f:facet name="title">
                    <p:outputLabel value="寄件者：#{inboxGroup.createUserName}　　"/>
                    <h:outputText value="#{inboxGroup.time}"
                                  style="font-weight: bold">
                    </h:outputText>
                </f:facet>
                <p:panelGrid columns="2"
                             styleClass="width100 marginTop10">
                    <p:panelGrid columns="2">
                        <p:outputLabel value="收件者："/>
                        <p:scrollPanel style="max-width: 1000px;border:none;" mode="native">
                            <p:outputLabel value="#{inboxGroup.send_to}"/>
                        </p:scrollPanel>
                    </p:panelGrid>
                    <p:panelGrid columns="1"
                                 styleClass="alignRight">
                        <p:commandButton value="訊息點閱狀況"
                                         actionListener="#{cc.attrs.model.clickGroupToStatus(inboxGroup.inbox_group_sid)}"
                                         onclick="showLoad();"
                                         oncomplete="hideLoad();"
                                         process="@this"/>
                    </p:panelGrid>
                </p:panelGrid>
                <p:panelGrid columns="2"
                             rendered="#{!inboxGroup.typeDep}">
                    <p:outputLabel value="留言訊息："/>
                    <p:outputLabel value="#{inboxGroup.message_css}"
                                   styleClass="colNormal breakAll"
                                   escape="false">
                    </p:outputLabel>
                </p:panelGrid>
            </p:tab>
        </p:accordionPanel>   

    </cc:implementation>
</ui:composition>

work-report/src/main/webapp/resources/components/multItemPicker_target_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:cp="http://java.sun.com/jsf/composite/components"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<!-- ================================= -->
<!--  已選取清單 -->
<!-- ================================= -->
<p:outputPanel styleClass="targetList_#{cc.attrs.componentID} coffee-block multItemPicker-selected-bk">
	<div class="coffee-block-header">
		<p:outputLabel value="#{cc.attrs.targetMenuTitle}" />
	</div>
	<p:dataTable
		id="targetListDatatable_#{cc.attrs.componentID}"
		widgetVar="targetListDatatable_#{cc.attrs.componentID}"
		value="#{currComponent.targetVO.allItems}"
		selection="#{currComponent.targetVO.selectedItems}"
		filteredValue="#{currComponent.targetVO.filteredItems}"
		var="targetItem"
		rowKey="#{targetItem.sid}"
		scrollHeight="#{(empty cc.attrs.menuHeight)?350:cc.attrs.menuHeight+16}"
		scrollable="true"
		selectionMode="multiple"
		rowStyleClass="multItemPicker-selected-bk"
		style="width:#{cc.attrs.menuWidth}px;"
		emptyMessage="尚未選擇">
		<f:facet name="emptyMessage">
			<span style='color: gray'>尚未選擇</span>
		</f:facet>
		<p:ajax
			event="rowDblselect"
			onstart="showLoad();clearFilters#{cc.attrs.componentID}('src');"
			listener="#{currComponent.event_TargetItemDoubleClick}"
			update="@(.#{cc.attrs.componentID}_MultItemPickerComponent)"
			oncomplete="hideLoad();" />
		<p:column
			filterBy="#{targetItem.name}"
			filterMatchMode="contains">
			<h:outputText
				rendered="#{not targetItem.active}"
				styleClass="WS1-1-2b"
				value="(停用)" />
			<h:outputText
				rendered="#{targetItem.disable}"
				styleClass="WS1-1-5b"
				value="(鎖定)" />
			<h:outputText
				value="#{targetItem.showName}"
				escape="false" />
		</p:column>
	</p:dataTable>
</p:outputPanel>
</html>

work-report/src/main/webapp/resources/components/workReportHeader.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:cc="http://java.sun.com/jsf/composite">

    <cc:interface>
        <cc:attribute name="model" shortDescription="WorkReportHeaderComponent物件"
                      type="com.cy.work.backend.web.view.components.WorkReportHeaderComponent" required="true"/>
        <cc:attribute name="model2" shortDescription="WorkReportHeaderComponent物件"
                      type="com.cy.work.backend.web.view.components.WorkReportBtnComponent"/>
        <cc:attribute name="edit" shortDescription="是否可編輯"
                      type="java.lang.Boolean" required="true"/>
        <cc:attribute name="editing" shortDescription="是否可點選回傳已讀取"
                      type="java.lang.Boolean" required="true"/>
        <cc:actionSource name="ActionEvent" targets="sendActionEvent"/>
    </cc:interface>
    <cc:implementation>
        <p:toolbar style="background: none !important;">
            <f:facet name="left">
                <p:panelGrid style="width: 1000px">
                    <p:row>
                        <p:column colspan="1">
                            <h:outputText value="&#160;&#160;&#160;" />
                            <p:outputLabel value="部門:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model.departmentName}" styleClass="reportTypeColor"/>
                        </p:column>
                        <p:column colspan="1">
                            <h:outputText value="&#160;&#160;&#160;" />
                            <p:outputLabel value="建立人員:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model.createUserName}" styleClass="reportTypeColor"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model.createTimeTitle}:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model.createTime}" styleClass="reportTypeColor"/>
                        </p:column>
                        <p:column colspan="1">
                            <h:outputText value="提交日期：" rendered="#{cc.attrs.model.submitTime != null}"/>
                        </p:column>
                        <p:column colspan="1">
                            <h:outputText value="#{cc.attrs.model.submitTime}"
                                          rendered="#{cc.attrs.model.submitTime != null}" styleClass="reportTypeColor"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model2.invalidCannotEnterReason}" style="color: red"/>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">
                            <h:outputText styleClass="column-label-require" />
                            <p:outputLabel value="標籤:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:selectOneMenu value="#{cc.attrs.model.tagID}" rendered="#{cc.attrs.edit}">
                                <f:selectItem itemLabel="請選擇" itemValue=""/>
                                <f:selectItems value="#{workProjectTagItemBean.activeWorkProjectTagItems}"/>
                            </p:selectOneMenu>
                            <p:outputLabel value="#{workProjectTagItemBean.getWorkProjectTagName(cc.attrs.model.tagID)}"
                                           rendered="#{!cc.attrs.edit}" styleClass="reportTypeColor"/>
                        </p:column>
                        <p:column colspan="1">
                            <h:outputText styleClass="column-label-require" />
                            <p:outputLabel value="編輯權限:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:selectOneMenu value="#{cc.attrs.model.acceptEditID}" rendered="#{cc.attrs.edit}">
                                <f:selectItem itemLabel="請選擇" itemValue=""/>
                                <f:selectItems value="#{workProjectAcceptEditItemBean.workProjectAcceptEditItems}"/>
                            </p:selectOneMenu>
                            <p:outputLabel
                                    value="#{workProjectAcceptEditItemBean.getWorkProjectAcceptEditName(cc.attrs.model.acceptEditID)}"
                                    styleClass="reportTypeColor" rendered="#{!cc.attrs.edit}"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="單號:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model.workProjectNo}" styleClass="reportTypeColor"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="狀態:"/>
                        </p:column>
                        <p:column colspan="1">
                            <p:outputLabel value="#{cc.attrs.model.status}" styleClass="reportTypeColor"/>
                        </p:column>

                    </p:row>
                </p:panelGrid>
            </f:facet>
            <f:facet name="right">
                <p:commandButton value="回傳已讀取" style="width:100px;height:60px" id="sendActionEvent"
                                 rendered="#{cc.attrs.model.showReadReceiptBtn}"
                                 disabled="#{!cc.attrs.model.readReceiptBtnAble || cc.attrs.editing}"></p:commandButton>
            </f:facet>
        </p:toolbar>
    </cc:implementation>
</ui:composition>