work-report/src/main/java/com/cy/work/backend/web/common/TransForwardTypeItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.work.backend.web.common.setting.TransFowardTypeSetting;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 轉寄類型Item Bean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@ManagedBean
public class TransForwardTypeItemBean {

    /** 取得 轉寄類型SelectItems */
    public List<SelectItem> getTransForwardTypesItems() {
        return TransFowardTypeSetting.getTransFowardTypesItems();
    }
}

work-report/src/main/java/com/cy/work/backend/web/common/TransReadStatusItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.work.backend.web.common.setting.TransReadStatusSetting;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 轉寄已未讀狀態Item Bean
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@ManagedBean
public class TransReadStatusItemBean  implements Serializable{

    private static final long serialVersionUID = -7072123483314014425L;

    /** 取得 轉寄已未讀狀態SelectItems */
    public List<SelectItem> getReadStatusItems() {
        return TransReadStatusSetting.getTransReadStatusItems();
    }
    
}

work-report/src/main/java/com/cy/work/backend/web/common/WorkProjectTagItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.common;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.backend.web.common.setting.WorkProjectTagItemSetting;
import com.cy.work.backend.web.logic.manager.WorkSettingOrgManager;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 標籤Item Bean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("request")
@Slf4j
@ManagedBean
public class WorkProjectTagItemBean implements Serializable {

    
    private static final long serialVersionUID = -101415460354603778L;

    @Autowired
    private WorkSettingOrgManager workSettingOrgManager;

    /** 取得 標籤SelectItems */
    public List<SelectItem> getWorkProjectTagItems() {
        try {
            return WorkProjectTagItemSetting.getWorkProjectTagItems(workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getWorkProjectTagItems ERROR", e);
        }
        return Lists.newArrayList();
    }

    public List<SelectItem> getActiveWorkProjectTagItems() {
        try {
            Integer loginUserDepSid = SecurityFacade.getPrimaryOrgSid();
            return WorkProjectTagItemSetting.getActiveWorkProjectTagItems(loginUserDepSid,
                    workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getActiveWorkProjectTagItems ERROR", e);
        }
        return Lists.newArrayList();
    }

    /** 標籤名稱 By tagID */
    public String getWorkProjectTagName(String tagID) {
        try {
        return WorkProjectTagItemSetting.getWorkProjectTagName(tagID,
                workSettingOrgManager.findByID(SecurityFacade.getCompanyId()).getSid());
        } catch (Exception e) {
            log.error("getWorkProjectTagName ERROR", e);
        }
        return "";
    }
}

work-report/src/main/java/com/cy/work/backend/web/web/view/Worp1Bean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.backend.web.web.view;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.backend.web.common.attachment.AttachmentComponent;
import com.cy.work.backend.web.common.attachment.AttachmentCondition;
import com.cy.work.backend.web.common.attachment.WPAttachmentComponent;
import com.cy.work.backend.web.common.setting.WorkProjectTagItemSetting;
import com.cy.work.backend.web.logic.components.OrgLogicComponents;
import com.cy.work.backend.web.logic.components.WRMasterLogicComponents;
import com.cy.work.backend.web.logic.components.WRUserLogicComponents;
import com.cy.work.backend.web.logic.utils.ToolsDate;
import com.cy.work.backend.web.util.pf.DisplayController;
import com.cy.work.backend.web.view.components.WorkReportDataComponent;
import com.cy.work.backend.web.view.components.WorkReportHeaderComponent;
import com.cy.work.backend.web.view.vo.OrgViewVo;
import com.cy.work.backend.web.view.vo.UserViewVO;
import com.cy.work.backend.web.vo.WRMaster;
import com.cy.work.backend.web.vo.enums.WREditType;
import com.cy.work.backend.web.vo.enums.WRStatus;
import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.omnifaces.util.Faces;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@Slf4j
@ManagedBean
public class Worp1Bean implements Serializable {

    
    private static final long serialVersionUID = 2408024711027739390L;
    @Autowired
    private WRUserLogicComponents wRUserLogicComponents;
    @Autowired
    private OrgLogicComponents orgLogicComponents;
    @Autowired
    private DisplayController displayController;
    @Autowired
    private WRMasterLogicComponents wRMasterLogicComponents;
    @Getter
    @Setter
    private WorkReportDataComponent workReportDataComponent;
    @Getter
    @Setter
    private WorkReportHeaderComponent workReportHeaderComponent;
    @Getter
    @Setter
    private List<AttachmentComponent> attachmentComponents;
    @Getter
    private WPAttachmentComponent wpAttachmentCompant;
    @Getter
    private String errorMessage;
    @Getter
    @Setter
    private Boolean edit = true;
    @Getter
    private UserViewVO userViewVO;
    @Getter
    private OrgViewVo depViewVo;
    @Getter
    private OrgViewVo compViewVo;

    private boolean canCrreateing = true;

    //private WkJsonUtils jsonUtils;
    @PostConstruct
    public void init() {
        userViewVO = wRUserLogicComponents.findBySid(SecurityFacade.getUserSid());
        depViewVo = orgLogicComponents.findBySid(SecurityFacade.getPrimaryOrgSid());
        compViewVo = orgLogicComponents.findById(SecurityFacade.getCompanyId());
        workReportDataComponent = new WorkReportDataComponent();
        workReportHeaderComponent = new WorkReportHeaderComponent();
        workReportHeaderComponent.setCreateUserName(userViewVO.getName());
        workReportHeaderComponent.setDepartmentName(depViewVo.getName());
        wpAttachmentCompant = new WPAttachmentComponent(userViewVO.getSid(), depViewVo.getSid());
        AttachmentCondition ac = new AttachmentCondition("", "", false);
        wpAttachmentCompant.loadAttachment(ac);
        attachmentComponents = Lists.newArrayList();

    }

    /** 主題欄位增加預設主題 */
    public void addSampleTitle() {
        try {
            if (Strings.isNullOrEmpty(workReportHeaderComponent.getTagID())) {
                Preconditions.checkState(false, "標籤尚未選擇，請確認！");
            }
            if (Strings.isNullOrEmpty(workReportDataComponent.getTitle())) {
                doAddSampleTitle();
            } else {
                DisplayController.getInstance().showPfWidgetVar("sampleTitleAlertDlgWv");
            }
        } catch (Exception e) {
            log.error("addSampleTitle Error", e);
            showMessage(e.getMessage());
        }
    }

    public void doAddSampleTitle() {
        try {
            if (Strings.isNullOrEmpty(workReportHeaderComponent.getTagID())) {
                Preconditions.checkState(false, "標籤尚未選擇，請確認！");
            }
            String tagName = WorkProjectTagItemSetting.getWorkProjectTagName(workReportHeaderComponent.getTagID(), compViewVo.getSid());
            String sampleTitle = userViewVO.getName() + "　[" + tagName + "]　" + ToolsDate.transDateToChineseString(new Date());
            workReportDataComponent.setTitle(sampleTitle);
            DisplayController.getInstance().hidePfWidgetVar("sampleTitleAlertDlgWv");
        } catch (Exception e) {
            log.error("doAddSampleTitle Error", e);
            showMessage(e.getMessage());
        }
    }

    public void doCreateWorkReport() {
        if (!this.canCrreateing) {
            return;
        }

        try {
            this.canCrreateing = false;
            WRMaster wr = wRMasterLogicComponents.createWRMaster(WRStatus.COMMIT, workReportDataComponent,
                    workReportHeaderComponent, wpAttachmentCompant.getSelectedAttachmentVOs(), userViewVO.getSid(), depViewVo.getSid(), compViewVo.getSid());
            DisplayController.getInstance().hidePfWidgetVar("commitAlertDlgWv");
            String url = "../worp/worp_iframe.xhtml?wrcId=" + wr.getSid();
            //log.info("ReLoad View " + url);
            Faces.getExternalContext().redirect(url);
        } catch (Exception e) {
            this.canCrreateing = true;
            log.error("createWorkReport", e);
            showMessage(e.getMessage());
        }
    }

    public void createWorkReport() {
        try {
            if (WREditType.PERSONAL.name().equals(workReportHeaderComponent.getAcceptEditID())) {
                DisplayController.getInstance().showPfWidgetVar("commitAlertDlgWv");
            } else {
                doCreateWorkReport();
            }
        } catch (Exception e) {
            log.error("createWorkReport", e);
            showMessage(e.getMessage());
        }
    }

    public void cancel() {
        try {
            String url = "../worp/worp1.xhtml";
            //log.info("ReLoad View " + url);
            Faces.getExternalContext().redirect(url);
        } catch (Exception e) {
            log.error("cancel", e);
            showMessage(e.getMessage());
        }
    }

    public void createTempWorkReport() {
        if (!this.canCrreateing) {
            return;
        }
        try {

            this.canCrreateing = false;
            WRMaster wr = wRMasterLogicComponents.createWRMaster(WRStatus.DRAFT, workReportDataComponent,
                    workReportHeaderComponent, wpAttachmentCompant.getSelectedAttachmentVOs(),
                    userViewVO.getSid(), depViewVo.getSid(),
                    compViewVo.getSid());
            String url = "../worp/worp_iframe.xhtml?wrcId=" + wr.getSid();
            //log.info("ReLoad View " + url);
            Faces.getExternalContext().redirect(url);

        } catch (Exception e) {
            this.canCrreateing = true;
            log.error("createTempWorkReport", e);
            showMessage(e.getMessage());
        }
    }

    /**
     * 顯示錯誤訊息及彈出Dialog
     *
     * @param message
     */
    private void showMessage(String message) {
        this.errorMessage = message;
        displayController.update("confirmDlgTemplate");
        displayController.showPfWidgetVar("confirmDlgTemplate");
    }

}

work-report/src/main/webapp/worp/pickUserComponents.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;"> 
]>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:cp="http://java.sun.com/jsf/composite/components"
      >
    <p:dialog header="#{pickUserDialogTitle}" widgetVar="#{pickUserDialogVar}" modal="true">
        <p:outputPanel id="#{pickUserDialogID}">
            <p:remoteCommand name="#{pickUserSearchMethodName}" actionListener="#{pickUserComponent.filterName()}" 
                             onstart="showLoad();"  oncomplete="hideLoad();" update="#{pickUserID}"
                             process="@this #{pickUserMemberID} #{pickUserID}" />
            <p:panelGrid columns="8" >
                <p:outputLabel value="部門"/>
                <p:commandButton icon="ui-icon-search"
                                 onclick="showLoad();" 
                                 update="#{pickUserSelDepDialogID}"
                                 oncomplete="hideLoad();PF('#{pickUserSelDepDialogVar}').show();"
                                 actionListener="#{pickUserComponent.loadSelectDepTree()}"
                                 process="@this #{pickUserID} #{pickUserMemberID}" />
                <p:outputLabel value="使用者暱稱"/>
                <p:inputText  id="#{pickUserMemberID}" placeholder="Search" value="#{pickUserComponent.filterNameValue}" onkeydown="executeScriptByEnter(event, '#{pickUserSearchMethodName}();');"  />
                <p:commandButton icon="ui-icon-search" 
                                 onclick="#{pickUserSearchMethodName}();" />

            </p:panelGrid>
            <p:pickList id="#{pickUserID}" value="#{pickUserComponent.pickUsers}" var="u"  converter="#{userViewVOConverter}"
                        itemLabel="#{u.name}" itemValue="#{u}"  itemDisabled="#{!u.moveAble}" 
                        >
                <f:facet name="sourceCaption"><h:outputText value="未選取清單"/></f:facet>  
                <f:facet name="targetCaption"><h:outputText value="已選取清單"/></f:facet>
                <p:column>  
                    <h:outputText value="#{u.departmentName} - #{u.name}"/>
                </p:column>
            </p:pickList>
            <p:panelGrid columns="2">
                <p:commandButton value="確定"  process="@this #{pickUserID}" update=":formTemplate:all_permission_tab"
                                 onclick="showLoad();" oncomplete="hideLoad();" actionListener="#{pickUserComponent.savePickList()}"/>    
                <p:commandButton value="取消" process="@this"  onclick="PF('#{pickUserDialogVar}').hide();" />
            </p:panelGrid>
        </p:outputPanel>
    </p:dialog>

    <p:dialog header="部門" widgetVar="#{pickUserSelDepDialogVar}" modal="true" resizable="false">
        <p:outputPanel id="#{pickUserSelDepDialogID}">
            <cp:depTree model="#{pickUserComponent.selectDepTreeManager}"  update="#{pickUserDialogID}" 
                        dlgName="#{pickUserSelDepDialogVar}"   btnShow="true" >
                <f:actionListener for="actionEvent"  binding="#{pickUserComponent.doSelectDep()}"/>
            </cp:depTree>
        </p:outputPanel>
    </p:dialog>

</html>

work-report/src/main/webapp/worp/workReportTransSearchComponents.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;"> 
]>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      >

    <p:panelGrid id="screen_view_query">
        <p:row>
            <p:column colspan="1">
                <p:outputLabel value="類型："/>
            </p:column>
            <p:column colspan="1">
                <p:selectOneMenu id="screen_view_query_categoryType"
                                 value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.selectTag}" style="width: 80px;" >
                    <f:selectItem itemLabel="全部"   itemValue="" />
                    <f:selectItems value="#{workProjectTagItemBean.workProjectTagItems}"   />
                </p:selectOneMenu>
            </p:column>
            <p:column colspan="1">
                <p:outputLabel value="是否閱讀："/>
            </p:column>
            <p:column colspan="1">
                <p:selectOneMenu value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.readStatus}" 
                                 style=" width: 80px" 
                                 styleClass="textEllipsis" >
                    <f:selectItem itemLabel="全部"   itemValue="" />
                    <f:selectItems value="#{transReadStatusItemBean.readStatusItems}"/>
                </p:selectOneMenu>
            </p:column>
            <p:column colspan="1" rendered="#{workReportTransSearchComponent.showSelectTransType}">
                <p:outputLabel value="寄發類型："/>
            </p:column>
            <p:column colspan="1" rendered="#{workReportTransSearchComponent.showSelectTransType}">
                <p:selectOneMenu value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.selectTransType}" 
                                 style=" width: 80px" 
                                 styleClass="textEllipsis" >
                    <f:selectItem itemLabel="全部"   itemValue="" />
                    <f:selectItems value="#{transForwardTypeItemBean.transForwardTypesItems}"/>
                </p:selectOneMenu>
            </p:column>
            <p:column colspan="1" >
                <p:outputLabel value="#{workReportTransSearchComponent.selectAllOrgTitleName}："/>
            </p:column>
            <p:column colspan="1">
                <p:commandButton icon="ui-icon-search"
                                 actionListener="#{workReportTransSearchComponent.loadAllDepTree()}"
                                 onclick="showLoad();" 
                                 oncomplete="hideLoad();"
                                 process="@this">
                </p:commandButton>
            </p:column>
            <p:column colspan="1"  rendered="#{workReportTransSearchComponent.showSelectBaseOrg}">
                <p:panelGrid columns="2">
                    <p:outputLabel value="寄發至："/>
                    <p:commandButton icon="ui-icon-search"
                                     actionListener="#{workReportTransSearchComponent.loadBaseDepTree()}"
                                     onclick="showLoad();" 
                                     oncomplete="hideLoad();"
                                     process="@this">
                    </p:commandButton>
                </p:panelGrid>
            </p:column>
        </p:row>
        <p:row>
            <p:column colspan="1">
                <p:outputLabel value="主題："/>
            </p:column>
            <p:column colspan="1">
                <p:inputText value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.title}" onkeydown="executeScriptByEnter(event, 'doSearchData();');" />
            </p:column>
            <p:column colspan="1">
                <p:outputLabel value="內容："/>
            </p:column>
            <p:column colspan="1">
                <p:inputText value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.content}" onkeydown="executeScriptByEnter(event, 'doSearchData();');"/>
            </p:column>
            <p:column colspan="1">
                <p:outputLabel value="#{workReportTransSearchComponent.personTitleName}："/>
            </p:column>
            <p:column colspan="1">
                <p:inputText value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.personName}" onkeydown="executeScriptByEnter(event, 'doSearchData();');"  />
            </p:column>
        </p:row>
        <p:row>
            <p:column colspan="1">
                <p:outputLabel value="模糊搜尋："/>
            </p:column>
            <p:column colspan="1">
                <p:inputText value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.allSearchText}" onkeydown="executeScriptByEnter(event, 'doSearchData();');" />
            </p:column>
            <p:column colspan="1"/>
            <p:column colspan="1" >
                <p:panelGrid columns="3">
                    <p:tabMenu id="dateBtn" activeIndex="#{workReportTransSearchComponent.workReportSearchHeaderComponent.dateTypeIndex}">
                        <p:menuitem value="上個月" process="@this updatedDate"  update="updatedDate @parent"  
                                    actionListener="#{workReportTransSearchComponent.workReportSearchHeaderComponent.changeDateIntervalPreMonth()}"
                                    />
                        <p:menuitem value="本月份" process="@this updatedDate"  update="updatedDate @parent"  
                                    actionListener="#{workReportTransSearchComponent.workReportSearchHeaderComponent.changeDateIntervalThisMonth()}"
                                    />
                        <p:menuitem value="下個月" process="@this updatedDate" update="updatedDate @parent"  
                                    actionListener="#{workReportTransSearchComponent.workReportSearchHeaderComponent.changeDateIntervalNextMonth()}"
                                    />

                    </p:tabMenu>
                </p:panelGrid>
            </p:column>
            <p:column colspan="1">
                <p:outputLabel value="寄發區間："/>
            </p:column>
            <p:column colspan="3">
                <p:outputPanel id="updatedDate">
                    <p:calendar value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.startDate}" 
                                navigator="true" mode="popup" 
                                showOn="button" pattern="yyyy/MM/dd" >
                    </p:calendar>
                    <p:outputLabel value="～"/>
                    <p:calendar value="#{workReportTransSearchComponent.workReportSearchHeaderComponent.endDate}" 
                                navigator="true" mode="popup" 
                                showOn="button" pattern="yyyy/MM/dd" >
                    </p:calendar>
                </p:outputPanel>
            </p:column>
            <p:column colspan="1">
                <p:outputPanel autoUpdate="true">
                    <p:panelGrid columns="2">
                        <p:commandButton value="搜尋" onclick="doSearchData()"
                                         process="@this">
                        </p:commandButton>
                        <p:commandButton value="清除"
                                         onclick="doClearData();" 
                                         oncomplete="hideLoad();"
                                         process="@this">
                        </p:commandButton>
                    </p:panelGrid>
                </p:outputPanel>
            </p:column>
        </p:row>
    </p:panelGrid>



</html>

work-report/src/main/webapp/worp/worp1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../template/templateProject.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:cp="http://java.sun.com/jsf/composite/components"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <f:metadata>
        <f:event type="preRenderView" listener="#{sessionTimerBean.reStartIdle()}"/>
    </f:metadata>
    <ui:define name="title">
        <h:outputText value="工作報告-草稿" />
    </ui:define>
    function myrefresh()
    {
    window.location.reload();
    }
    <ui:define name="content">
        <p:outputPanel id="workReportHeaderPanel">
            <cp:workReportHeader model="#{worp1Bean.workReportHeaderComponent}"  edit="#{worp1Bean.edit}" editing="#{worp1Bean.edit}">
            </cp:workReportHeader>
        </p:outputPanel>

        <p:outputPanel id="workReportDataPanel">
            <cp:workReportData model="#{worp1Bean.workReportDataComponent}" process="workReportHeaderPanel"  edit="#{worp1Bean.edit}">
                <f:actionListener for="actionEvent" binding="#{worp1Bean.addSampleTitle()}"/>
                <f:actionListener for="doSampleActionEvent" binding="#{worp1Bean.doAddSampleTitle()}"/>
            </cp:workReportData>
        </p:outputPanel>
        <p:panelGrid columns="2" >
            <h:panelGroup>
                <h:outputText value="附加檔案："/>
            </h:panelGroup>
            <p:outputPanel id="attachemtUploadPanel">
                <p:commandButton value="附加檔案" 
                                 onclick="showLoad();"
                                 process="@this"  
                                 oncomplete="PF('dlgUploadWv').show();hideLoad();" 
                                 />
                <cp:attachmentUpload model="#{worp1Bean.wpAttachmentCompant}" process="attachemtViewPanel" uploadDialogWv="dlgUploadWv" uploadDialogId="dlgUploadId" update="attachemtViewPanel" >

                </cp:attachmentUpload>
            </p:outputPanel>
        </p:panelGrid>
        <p:outputPanel id="attachemtViewPanel">
            <cp:attachmentView model="#{worp1Bean.wpAttachmentCompant}"></cp:attachmentView>
        </p:outputPanel>
        <p:commandButton value="確認"  onclick="showLoad();saveHTML('workReportData_content');saveHTML('workReportData_remark');" oncomplete="hideLoad();" update="workReportDataPanel workReportHeaderPanel"  process="@this workReportDataPanel workReportHeaderPanel attachemtViewPanel" actionListener="#{worp1Bean.createWorkReport}"/>
        <p:commandButton value="取消" actionListener="#{worp1Bean.cancel()}" />
        <p:commandButton value="儲存草稿"  onclick="showLoad();saveHTML('workReportData_content');saveHTML('workReportData_remark');" oncomplete="hideLoad();" update="workReportDataPanel workReportHeaderPanel"  process="@this workReportDataPanel workReportHeaderPanel attachemtViewPanel" actionListener="#{worp1Bean.createTempWorkReport}"/>

        <p:confirmDialog id="confirmDlgTemplate"  widgetVar="confirmDlgTemplate" >
            <f:facet name="message">
                <h:outputText value="#{worp1Bean.errorMessage}" escape="false"/>
            </f:facet>
            <p:commandButton value="確認" type="button" onclick="PF('confirmDlgTemplate').hide()"/>
        </p:confirmDialog>


        <p:confirmDialog id="commitAlertDlg"  widgetVar="commitAlertDlgWv" >
            <f:facet name="message">
                <h:outputText value="存檔後不可進行修改，請確認！" escape="false"/>
            </f:facet>
            <p:commandButton value="確認" onclick="showLoad();saveHTML('workReportData_content');saveHTML('workReportData_remark');" oncomplete="hideLoad();" update="workReportDataPanel workReportHeaderPanel"  process="@this workReportDataPanel workReportHeaderPanel attachemtViewPanel" actionListener="#{worp1Bean.doCreateWorkReport()}" />
            <p:commandButton value="取消"  process="@this" onclick="PF('commitAlertDlgWv').hide()" />
        </p:confirmDialog>


    </ui:define>

</ui:composition>